### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by k4r3l01** [krzesu0/MessLogger#1]
Hello please its will be possible to add feature to log to file by thread_id i mean one file per thread_id.
and its will be possible to make local translate by dictionary because you say translate by fbchat is buggy.thanks in advance for you work

**Comment by mlodybercik** [comment]
> Hello please its will be possible to add feature to log to file by thread_id i mean one file per thread_id.

I added it in 1aca6d2, set flags like this to dump every message to file in folder `history/<threadID>/<date>`
```python
default = {
# Max length of given thread history.
"LENGTH": 1000,

# Log to arr
"LOG": False,

# Log to console current messages
"LOG_TO_CONSOLE": False,

# Dump contents of LenArray to thread files after logout
"DUMP_CONTENTS": False,

# Live logging to file, useful when leaving it over longer span of time
"LIVE_LOG": True
}
```
---
> and its will be possible to make local translate by dictionary because you say translate by fbchat is buggy.thanks in advance for you work

Yeah, I'll work on it, I'll find some way to make it work...

**Comment by k4r3l01** [comment]
thanks its working and about creating local dictionary i make this

```
mydict = {'facebook id': 'name',
                'facebook id': 'name2'}
		if mydict.get(authorID) is not None:
			authorID = mydict.get(authorID)
		if mydict.get(threadID) is not None:
			threadID = mydict.get(threadID)
```
and added to log function to line 130 before content =

**Comment by mlodybercik** [comment]
Yeah, I have an idea how to get this to work. I'll implement this ASAP.
